core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce import models as tinymce_models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description_title = models.TextField(null=True)
    description = tinymce_models.HTMLField()
    video = models.URLField(max_length=300, default='https://www.youtube.com/embed/')
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

class FerWidget(models.Model):
    titleFer = models.CharField(max_length=255)
    descriptionFer = tinymce_models.HTMLField()
    img = models.ImageField(upload_to='images/', default='images/default.png')

    def __str__(self):
        return self.titleFer

class ComunicationsLinks(models.Model):
    facebook = models.URLField(max_length=255, null=True)
    instagram = models.URLField(max_length=255, null=True)
    pinterest = models.URLField(max_length=255, null=True)
    whatsapp = models.URLField(max_length=255, null=True)
    blog = models.URLField(max_length=255, null=True)

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, FerWidget, ComunicationsLinks
from django.core.paginator import Paginator

# Create your views here.
def catigories(request):
    return {
        'catigories':Category.objects.all() 
    }

def home(request):
    products = Product.objects.all()
    #set up pagination
    p = Paginator(Product.objects.all(), 6)
    page = request.GET.get('page')
    productsss = p.get_page(page)
    ferwidget = FerWidget.objects.all()
    comunicationslinks = get_object_or_404(ComunicationsLinks)
    return render(request, 'store/home.html', {'products':products, 'productsss':productsss ,'ferwidget':ferwidget, 'comunicationslinks':comunicationslinks})

def about(request):
    ferwidget = FerWidget.objects.all()
    comunicationslinks = get_object_or_404(ComunicationsLinks)
    return render(request, 'store/about.html', {'ferwidget':ferwidget, 'comunicationslinks':comunicationslinks})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    ferwidget = FerWidget.objects.all()
    comunicationslinks = get_object_or_404(ComunicationsLinks)
    return render(request, 'store/products/detail.html', {'product': product, 'ferwidget':ferwidget, 'comunicationslinks':comunicationslinks})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    ferwidget = FerWidget.objects.all()
    comunicationslinks = get_object_or_404(ComunicationsLinks)
    return render(request, 'store/products/category.html', {'category': category, 'products': products, 'ferwidget':ferwidget, 'comunicationslinks':comunicationslinks})

templates/store/about.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
<h1>Contacto</h1>
<div class="card text-center">
    <div class="card-header">
      WhatsApp
      <svg style="color: green;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
        <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
      </svg>
    </div>
    <div class="card-body">
        <img style="width: 35%;" src="{% static '/img/ferrrr.png' %}" class="rounded-circle" alt="asdf" srcset="">
        <br><br>
        <h5 class="card-title">Fernando Natanael</h5>
        <p class="card-text">👇 +52 1 744 313 4670 👇</p>
        <a href="{{ comunicationslinks.whatsapp }}" class="btn btn-primary">contactar</a>
    </div>
    <div class="card-footer text-muted">
      {{ product.created }}
    </div>
</div>
{% endblock content %}

templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>villa</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/home.css' %}" rel="stylesheet" />

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Grand+Hotel&display=swap" rel="stylesheet">
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Villas Bahia Dorada</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                              <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'store:about' %}">Contacto</a>
                              </li>
                            </ul>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
        <!--Baner-->
        <header class="py-5 text-center mb-5 text-black" style="background-image: url('static/img/Acapulco_México_banner(6).jpg');">
            <h1 style="font-family: 'Grand Hotel', cursive;">Bienvenido al blog de las Bahia's!</h1>
            <p style="font-family: 'Grand Hotel', cursive;" class="lead mb-0">actividades divertidas que puedes hacer con toda la familia</p>
        </header>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        
                    </div>
                    <!-- Nested row for non-featured blog posts-->
                    <div class="row">
                        <div class="col">
                            {% block content %}{% endblock %}
                        </div>
                    </div>
                    
                </div>
                <br>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Contacto</div>
                        <div class="card-body">
                            <div class="text-center input-group">
                                <a class="col" href="{{ comunicationslinks.facebook }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                                        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                                    </svg>
                                </a>
                                <a class="col" style="color: #FF6161;" href="{{ comunicationslinks.instagram }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                                        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                                    </svg>
                                </a>
                                <a class="col" style="color: red;" href="{{ comunicationslinks.pinterest }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-pinterest" viewBox="0 0 16 16">
                                        <path d="M8 0a8 8 0 0 0-2.915 15.452c-.07-.633-.134-1.606.027-2.297.146-.625.938-3.977.938-3.977s-.239-.479-.239-1.187c0-1.113.645-1.943 1.448-1.943.682 0 1.012.512 1.012 1.127 0 .686-.437 1.712-.663 2.663-.188.796.4 1.446 1.185 1.446 1.422 0 2.515-1.5 2.515-3.664 0-1.915-1.377-3.254-3.342-3.254-2.276 0-3.612 1.707-3.612 3.471 0 .688.265 1.425.595 1.826a.24.24 0 0 1 .056.23c-.061.252-.196.796-.222.907-.035.146-.116.177-.268.107-1-.465-1.624-1.926-1.624-3.1 0-2.523 1.834-4.84 5.286-4.84 2.775 0 4.932 1.977 4.932 4.62 0 2.757-1.739 4.976-4.151 4.976-.811 0-1.573-.421-1.834-.919l-.498 1.902c-.181.695-.669 1.566-.995 2.097A8 8 0 1 0 8 0z"/>
                                    </svg>
                                </a>
                                <a class="col" style="color: green;" href="{{ comunicationslinks.whatsapp }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
                                        <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z"/>
                                    </svg>
                                </a>
                                <a class="col" style="color: blue;" href="{{ comunicationslinks.blog }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-droplet-fill" viewBox="0 0 16 16">
                                        <path d="M8 16a6 6 0 0 0 6-6c0-1.655-1.122-2.904-2.432-4.362C10.254 4.176 8.75 2.503 8 0c0 0-6 5.686-6 10a6 6 0 0 0 6 6ZM6.646 4.646l.708.708c-.29.29-1.128 1.311-1.907 2.87l-.894-.448c.82-1.641 1.717-2.753 2.093-3.13Z"/>
                                    </svg>
                                </a>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        {% for c in catigories %}
                                            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                                <a href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Side widget-->
                    {% for fer in ferwidget %}
                    <div class="card mb-4">
                        <div class="card-header">{{ fer.titleFer }}</div>
                        <div class="card-body">{{ fer.descriptionFer|safe }}</div>
                        <img src="{{ fer.img.url }}" alt="" srcset="">
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Villas Bahia Dorada 2022</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

templates/store/home.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
<div class="row align-items-center">
    {% for product in productsss %}
      <div class="col-lg-6">
        <div class="card mb-4">
          <a href="#!"><img class="card-img-top" src="{{ product.image.url }}" alt="..." /></a>
            <div class="card-body">
              <div class="small text-muted">{{ product.created }}</div>
              <h2 class="card-title h4">{{ product.title }}</h2>
              <p class="card-text">{{ product.description_title|slice:"90" }}...</p>
              <a class="btn btn-primary" href="{{ product.get_absolute_url }}">leer mas →</a>
            </div>
        </div>
      </div>
    {% endfor %}
</div>
página {{ productsss.number }} / {{ productsss.paginator.num_pages }}
<!-- Pagination-->
<nav aria-label="Pagination">
  <hr class="my-0" />
  <ul class="pagination justify-content-center my-4">
      <!--<li class="page-item"><a class="page-link" href="?page=1">&laquo first</a></li>-->
      {% if productsss.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ productsss.previous_page_number }}">previous</a></li>
      {% endif %}

      {% for num_page in productsss.paginator.page_range %}
        {% if productsss.number == num_page %}
          <li class="page-item active"><a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ num_page }}">{{ num_page }}</a></li>
        {% endif %}
      {% endfor %}

      {% if productsss.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ productsss.next_page_number }}">next</a></li>
      {% endif %}
  </ul>
  <br>
</nav>
{% endblock content %}

templates/store/products/category.html
{% extends 'store/base.html' %}

{% block content %}
<h1>{{category.name|title}}</h1>
<div class="row align-items-center">
    {% for product in products %}
    <div class="col-lg-6">
      <div class="card mb-4">
        <a href="#!"><img class="card-img-top" src="{{ product.image.url }}" alt="..." /></a>
          <div class="card-body">
            <div class="small text-muted">{{ product.created }}</div>
            <h2 class="card-title h4">{{ product.title }}</h2>
            <p class="card-text">{{ product.description_title|slice:"90" }}...</p>
            <a class="btn btn-primary" href="{{ product.get_absolute_url }}">leer mas →</a>
          </div>
      </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/store/products/detail.html
{% extends "store/base.html" %}
{% load static %}{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<article>
    <!-- Post header-->
    <header class="mb-4">
        <!-- Post title-->
        <h1 class="fw-bolder mb-1">{{ product.title }}</h1>
        <!-- Post meta content-->
        <div class="text-muted fst-italic mb-2">{{ product.created }}</div>
        <!-- Post categories-->
        <a class="badge bg-secondary text-decoration-none link-light" href="#!">{{ product.category }}</a>
        <a class="badge bg-secondary text-decoration-none link-light" href="#!">{{ product.created_by }}</a>
    </header>
    <!-- Preview image figure-->
    <figure class="mb-4"><img class="img-fluid rounded" src="{{ product.image.url }}" alt="..." /></figure>
    <!-- Post content-->
    <section class="mb-5">
        <p class="fs-5 mb-4">{{ product.description|safe }}</p>
        <iframe width="100%" height="400" src="{{ product.video }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </section>
</article>
{% endblock %}